# Generated by Django 4.1.3 on 2022-11-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
